/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
import { describe, it, expect } from 'vitest';
import { generateRoomId, validateRoomId } from './utils';

describe('generateRoomId', () => {
  it('should return an 8-character string', () => {
    const roomId = generateRoomId();
    expect(roomId).toHaveLength(8);
    expect(typeof roomId).toBe('string');
  });

  it('should return unique IDs on repeated calls', () => {
    const id1 = generateRoomId();
    const id2 = generateRoomId();
    const id3 = generateRoomId();

    expect(id1).not.toBe(id2);
    expect(id2).not.toBe(id3);
    expect(id1).not.toBe(id3);
  });

  it('should only contain alphanumeric characters', () => {
    const roomId = generateRoomId();
    expect(roomId).toMatch(/^[a-zA-Z0-9]+$/);
  });

  it('should generate 100 unique IDs', () => {
    const ids = new Set<string>();
    for (let i = 0; i < 100; i++) {
      ids.add(generateRoomId());
    }
    expect(ids.size).toBe(100);
  });
});

describe('validateRoomId', () => {
  it('should accept valid 8-character alphanumeric strings', () => {
    expect(validateRoomId('abcd1234')).toBe(true);
    expect(validateRoomId('ABCD1234')).toBe(true);
    expect(validateRoomId('aBcD1234')).toBe(true);
    expect(validateRoomId('12345678')).toBe(true);
    expect(validateRoomId('abcdefgh')).toBe(true);
    expect(validateRoomId('ABCDEFGH')).toBe(true);
  });

  it('should reject strings that are too short', () => {
    expect(validateRoomId('abc123')).toBe(false);
    expect(validateRoomId('a')).toBe(false);
    expect(validateRoomId('')).toBe(false);
  });

  it('should reject strings that are too long', () => {
    expect(validateRoomId('abcd12345')).toBe(false);
    expect(validateRoomId('abcd1234567890')).toBe(false);
  });

  it('should reject strings with special characters', () => {
    expect(validateRoomId('abcd-123')).toBe(false);
    expect(validateRoomId('abcd_123')).toBe(false);
    expect(validateRoomId('abcd 123')).toBe(false);
    expect(validateRoomId('abcd!123')).toBe(false);
    expect(validateRoomId('abcd@123')).toBe(false);
    expect(validateRoomId('abcd#123')).toBe(false);
  });

  it('should reject empty string', () => {
    expect(validateRoomId('')).toBe(false);
  });

  it('should reject null and undefined', () => {
    expect(validateRoomId(null as any)).toBe(false);
    expect(validateRoomId(undefined as any)).toBe(false);
  });

  it('should reject non-string values', () => {
    expect(validateRoomId(12345678 as any)).toBe(false);
    expect(validateRoomId({} as any)).toBe(false);
    expect(validateRoomId([] as any)).toBe(false);
  });

  it('should accept IDs generated by generateRoomId', () => {
    const roomId = generateRoomId();
    expect(validateRoomId(roomId)).toBe(true);
  });
});
