/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars, @typescript-eslint/no-unsafe-function-type, no-constant-binary-expression */
/**
 * COMPREHENSIVE SECOND PLAYER SPECTATOR BUG REPRODUCTION TESTS
 *
 * Critical Bug Description:
 * =======================
 * 1. Tab 1 creates room → becomes Player X ✓
 * 2. Tab 2 joins room → Tab 1 disconnects ✗
 * 3. Tab 2 becomes spectator (WRONG - should be Player O) ✗
 * 4. Multiplayer is completely broken ✗
 *
 * Test Strategy:
 * =============
 * - Part 1: Presence Tracking Tests (verify Ably presence state)
 * - Part 2: Role Assignment Logic Tests (verify determineRole function)
 * - Part 3: Channel State Tests (verify channels stay attached)
 * - Part 4: Client ID Verification (verify ID consistency)
 * - Part 5: Integration Tests (full two-player flow)
 * - Part 6: Actual Code Inspection (test real implementation behavior)
 *
 * Expected Results:
 * ================
 * ALL TESTS SHOULD FAIL until the bug is fixed!
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderHook, waitFor, act } from '@testing-library/react';
import type * as Ably from 'ably';

// ============================================================================
// REALISTIC ABLY MOCK SETUP
// ============================================================================

interface MockPresenceMember {
  clientId: string;
  data: { role: 'X' | 'O' | 'spectator' };
}

// Global presence state shared across all mock channels for the same room
const roomPresenceMap = new Map<string, MockPresenceMember[]>();

// Track presence callbacks per room
const presenceCallbacksMap = new Map<string, Set<Function>>();

// Track channel instances and their state
interface ChannelState {
  state: 'initialized' | 'attaching' | 'attached' | 'detaching' | 'detached' | 'failed';
  instanceId: string;
  clientId: string;
}
const channelStatesMap = new Map<string, ChannelState[]>();

// Track the last clientId generated by nanoid
let lastGeneratedClientId: string | null = null;

/**
 * Creates a realistic Ably channel mock that tracks presence across tabs
 */
function createRealisticAblyMock(roomId: string, clientId: string): any {
  const instanceId = `channel-${Date.now()}-${Math.random()}`;

  console.log(`[MOCK] Creating channel instance ${instanceId} for room ${roomId} with clientId ${clientId}`);

  // Initialize room presence if not exists
  if (!roomPresenceMap.has(roomId)) {
    roomPresenceMap.set(roomId, []);
  }

  // Initialize callback set for this room
  if (!presenceCallbacksMap.has(roomId)) {
    presenceCallbacksMap.set(roomId, new Set());
  }

  // Track this channel instance
  if (!channelStatesMap.has(roomId)) {
    channelStatesMap.set(roomId, []);
  }
  const channelStates = channelStatesMap.get(roomId)!;
  const channelState: ChannelState = { state: 'attached', instanceId, clientId };
  channelStates.push(channelState);

  const callbackSet = new Set<Function>();

  const mockPresence = {
    /**
     * Get current presence members for this room
     */
    get: vi.fn().mockImplementation(async () => {
      const members = roomPresenceMap.get(roomId) || [];
      console.log(`[MOCK PRESENCE] ${clientId} get() → ${members.length} members:`,
        members.map(m => `${m.clientId}:${m.data.role}`).join(', '));
      return [...members]; // Return a copy
    }),

    /**
     * Enter presence with role data
     */
    enter: vi.fn().mockImplementation(async (data: { role: 'X' | 'O' | 'spectator' }) => {
      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 10));

      const members = roomPresenceMap.get(roomId) || [];
      const existingIndex = members.findIndex(m => m.clientId === clientId);

      if (existingIndex >= 0) {
        // Update existing member
        members[existingIndex] = { clientId, data };
        console.log(`[MOCK PRESENCE] ${clientId} enter() - UPDATED to role ${data.role}`);
      } else {
        // Add new member
        members.push({ clientId, data });
        console.log(`[MOCK PRESENCE] ${clientId} enter() - ADDED as ${data.role}`);
      }

      roomPresenceMap.set(roomId, members);

      // Notify all subscribers in this room
      const callbacks = presenceCallbacksMap.get(roomId);
      if (callbacks) {
        callbacks.forEach(callback => {
          callback({
            action: 'enter',
            clientId,
            data,
          });
        });
      }
    }),

    /**
     * Leave presence
     */
    leave: vi.fn().mockImplementation(async () => {
      const members = roomPresenceMap.get(roomId) || [];
      const filtered = members.filter(m => m.clientId !== clientId);
      roomPresenceMap.set(roomId, filtered);

      console.log(`[MOCK PRESENCE] ${clientId} leave() - removed from presence`);

      // Notify all subscribers
      const callbacks = presenceCallbacksMap.get(roomId);
      if (callbacks) {
        callbacks.forEach(callback => {
          callback({
            action: 'leave',
            clientId,
          });
        });
      }
    }),

    /**
     * Subscribe to presence updates
     */
    subscribe: vi.fn().mockImplementation((callback: Function) => {
      callbackSet.add(callback);
      const roomCallbacks = presenceCallbacksMap.get(roomId)!;
      roomCallbacks.add(callback);

      console.log(`[MOCK PRESENCE] ${clientId} subscribe() - total callbacks: ${roomCallbacks.size}`);
    }),

    /**
     * Unsubscribe from presence updates
     */
    unsubscribe: vi.fn().mockImplementation(() => {
      const roomCallbacks = presenceCallbacksMap.get(roomId)!;
      callbackSet.forEach(callback => roomCallbacks.delete(callback));
      callbackSet.clear();

      console.log(`[MOCK PRESENCE] ${clientId} unsubscribe()`);
    }),
  };

  const mockChannel = {
    name: `room:${roomId}`,
    presence: mockPresence,
    state: 'attached',

    subscribe: vi.fn(),
    publish: vi.fn().mockResolvedValue(undefined),
    unsubscribe: vi.fn(),

    detach: vi.fn().mockImplementation(async () => {
      // Mark this channel instance as detached
      const states = channelStatesMap.get(roomId);
      const state = states?.find(s => s.clientId === clientId);
      if (state) {
        state.state = 'detached';
      }

      console.log(`[MOCK CHANNEL] ${clientId} detach()`);
    }),

    // For debugging
    _clientId: clientId,
    _instanceId: instanceId,
  };

  return mockChannel;
}

// Mock ably-client
vi.mock('../ably-client', () => ({
  ablyClient: {
    auth: {
      // Return undefined so useRoom falls back to nanoid()
      clientId: undefined,
    },
    connection: {
      state: 'connected',
      on: vi.fn(),
    },
    channels: {
      get: vi.fn((channelName: string) => {
        const roomId = channelName.replace('room:', '');
        const clientId = lastGeneratedClientId || 'unknown';

        // Each call creates a NEW channel instance (simulates multiple tabs)
        return createRealisticAblyMock(roomId, clientId);
      }),
    },
    close: vi.fn(),
  },
}));

// Mock utils
vi.mock('../utils', () => ({
  generateRoomId: vi.fn(() => 'testroom'),
  validateRoomId: vi.fn((id: string) => id.length === 8 && /^[a-zA-Z0-9]{8}$/.test(id)),
}));

// Mock nanoid to generate unique IDs per hook instance
let nanoidCallCount = 0;
vi.mock('nanoid', () => ({
  nanoid: vi.fn(() => {
    nanoidCallCount++;
    const id = `client-${nanoidCallCount}`;
    lastGeneratedClientId = id;
    console.log(`[MOCK NANOID] Generated client ID: ${id}`);
    return id;
  }),
}));

// Import AFTER mocks are set up
import { useRoom } from '../useRoom';

// ============================================================================
// TEST SUITE
// ============================================================================

describe('COMPREHENSIVE Second Player Spectator Bug Tests', () => {
  beforeEach(() => {
    // Reset all state
    vi.clearAllMocks();
    nanoidCallCount = 0;
    lastGeneratedClientId = null;
    roomPresenceMap.clear();
    presenceCallbacksMap.clear();
    channelStatesMap.clear();

    console.log('\n========================================');
    console.log('TEST STARTING');
    console.log('========================================\n');
  });

  afterEach(() => {
    console.log('\n========================================');
    console.log('TEST COMPLETED');
    console.log('========================================\n');
  });

  // ==========================================================================
  // PART 1: PRESENCE TRACKING TESTS
  // ==========================================================================

  describe('Part 1: Presence Tracking', () => {
    it('should track first player correctly in presence', async () => {
      console.log('[PART 1] Testing: First player in presence tracking\n');

      // Create room
      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => {
        expect(tab1.current.isConnected).toBe(true);
      });

      // Get presence members
      const members = roomPresenceMap.get(roomId) || [];

      console.log('[TEST] Tab 1 localPlayerId:', tab1.current.localPlayerId);
      console.log('[TEST] Presence members:', members);
      console.log('[TEST] Member count:', members.length);
      if (members.length > 0) {
        console.log('[TEST] First member clientId:', members[0].clientId);
        console.log('[TEST] First member role:', members[0].data.role);
      }

      // First player should be in presence
      expect(members).toHaveLength(1);
      expect(members[0].clientId).toBe(tab1.current.localPlayerId);
      expect(members[0].data.role).toBe('X');
    });

    it('should track both players in presence when second joins', async () => {
      console.log('[PART 1] Testing: Both players in presence\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const tab1ClientId = tab1.current.localPlayerId;

      // Tab 2 joins
      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      const tab2ClientId = tab2.current.localPlayerId;

      // Check presence
      const members = roomPresenceMap.get(roomId) || [];

      console.log('[TEST] Tab 1 clientId:', tab1ClientId);
      console.log('[TEST] Tab 2 clientId:', tab2ClientId);
      console.log('[TEST] Presence members:', members.map(m => `${m.clientId}:${m.data.role}`));
      console.log('[TEST] Total members:', members.length);

      // Should see 2 members
      expect(members).toHaveLength(2);

      // Verify both clients are in presence
      const memberIds = members.map(m => m.clientId);
      expect(memberIds).toContain(tab1ClientId);
      expect(memberIds).toContain(tab2ClientId);
    });

    it('should NOT remove first player when second joins', async () => {
      console.log('[PART 1] Testing: First player stays in presence when second joins\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const tab1ClientId = tab1.current.localPlayerId;

      // Verify Tab 1 is in presence
      const beforeJoin = roomPresenceMap.get(roomId) || [];
      console.log('[BUG CHECK] Before Tab 2 join:', beforeJoin.map(m => m.clientId));

      expect(beforeJoin.map(m => m.clientId)).toContain(tab1ClientId);

      // Tab 2 joins
      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      // Wait for presence to sync
      await new Promise(resolve => setTimeout(resolve, 100));

      // Tab 1 should STILL be in presence
      const afterJoin = roomPresenceMap.get(roomId) || [];
      console.log('[BUG CHECK] After Tab 2 join:', afterJoin.map(m => m.clientId));
      console.log('[BUG CHECK] Tab 1 clientId:', tab1ClientId);

      // CRITICAL: This will fail if Tab 1 gets removed
      expect(afterJoin.map(m => m.clientId)).toContain(tab1ClientId);
    });

    it('should maintain correct presence order (X first, O second)', async () => {
      console.log('[PART 1] Testing: Presence order (X before O)\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      const members = roomPresenceMap.get(roomId) || [];

      console.log('[TEST] Presence order:', members.map(m => `${m.clientId}:${m.data.role}`));

      // First member should be X
      expect(members[0].data.role).toBe('X');

      // Second member should be O
      expect(members[1].data.role).toBe('O');
    });
  });

  // ==========================================================================
  // PART 2: ROLE ASSIGNMENT LOGIC TESTS
  // ==========================================================================

  describe('Part 2: Role Assignment Logic', () => {
    it('should assign X to first player in empty room', async () => {
      console.log('[PART 2] Testing: First player gets X role\n');

      const { result } = renderHook(() => useRoom(null));

      await act(async () => {
        await result.current.createRoom();
      });

      await waitFor(() => expect(result.current.isConnected).toBe(true));

      console.log('[TEST] First player role:', result.current.playerRole);
      console.log('[TEST] Expected: X');

      expect(result.current.playerRole).toBe('X');
      expect(result.current.playerRole).not.toBe('O');
      expect(result.current.playerRole).not.toBe('spectator');
    });

    it('should assign O to second player when X exists', async () => {
      console.log('[PART 2] Testing: Second player gets O role\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      console.log('[TEST] Tab 1 (creator) role:', tab1.current.playerRole);
      expect(tab1.current.playerRole).toBe('X');

      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      console.log('[TEST] Tab 2 (second joiner) role:', tab2.current.playerRole);
      console.log('[TEST] Expected: O');

      // CRITICAL: Second player should be O, NOT spectator
      expect(tab2.current.playerRole).toBe('O');
      expect(tab2.current.playerRole).not.toBe('spectator');
      expect(tab2.current.playerRole).not.toBe('X');
    });

    it('should assign spectator to third player when X and O exist', async () => {
      console.log('[PART 2] Testing: Third player gets spectator role\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      const { result: tab3 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab3.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab3.current.isConnected).toBe(true));

      console.log('[TEST] Tab 1 role:', tab1.current.playerRole);
      console.log('[TEST] Tab 2 role:', tab2.current.playerRole);
      console.log('[TEST] Tab 3 role:', tab3.current.playerRole);

      expect(tab1.current.playerRole).toBe('X');
      expect(tab2.current.playerRole).toBe('O');
      expect(tab3.current.playerRole).toBe('spectator');
    });

    it('should NOT reassign roles when presence updates', async () => {
      console.log('[PART 2] Testing: Roles stay stable during presence updates\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const tab1InitialRole = tab1.current.playerRole;
      console.log('[TEST] Tab 1 initial role:', tab1InitialRole);

      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      // Wait for presence updates to propagate
      await new Promise(resolve => setTimeout(resolve, 200));

      console.log('[TEST] Tab 1 role after Tab 2 joined:', tab1.current.playerRole);
      console.log('[TEST] Tab 1 role changed?', tab1InitialRole !== tab1.current.playerRole);

      // CRITICAL: Tab 1 role should NOT change
      expect(tab1.current.playerRole).toBe(tab1InitialRole);
      expect(tab1.current.playerRole).toBe('X');
    });
  });

  // ==========================================================================
  // PART 3: CHANNEL STATE TESTS
  // ==========================================================================

  describe('Part 3: Channel State When Second Player Joins', () => {
    it('Tab 1 channel should stay attached when Tab 2 joins', async () => {
      console.log('[PART 3] Testing: Tab 1 channel stays attached\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const tab1ChannelBefore = tab1.current.channel;
      console.log('[TEST] Tab 1 channel before Tab 2 joins:', tab1ChannelBefore?.state);

      expect(tab1ChannelBefore?.state).toBe('attached');

      // Tab 2 joins
      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      // Give time for any side effects
      await new Promise(resolve => setTimeout(resolve, 100));

      console.log('[TEST] Tab 1 channel after Tab 2 joins:', tab1.current.channel?.state);
      console.log('[TEST] Tab 1 channel is same object?', tab1ChannelBefore === tab1.current.channel);
      console.log('[TEST] Tab 1 isConnected:', tab1.current.isConnected);

      // CRITICAL: Tab 1 channel should STILL be attached
      expect(tab1.current.channel).toBeTruthy();
      expect(tab1.current.channel?.state).toBe('attached');
      expect(tab1.current.isConnected).toBe(true);
    });

    it('Tab 1 should not call detach when Tab 2 joins', async () => {
      console.log('[PART 3] Testing: Tab 1 detach should not be called\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const tab1Channel = tab1.current.channel;
      const detachSpy = tab1Channel?.detach;

      console.log('[TEST] Tab 1 channel detach spy set up');

      // Tab 2 joins
      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      // Give time for any side effects
      await new Promise(resolve => setTimeout(resolve, 100));

      console.log('[TEST] Detach called?', (detachSpy as any)?.mock?.calls?.length || 0);

      // Tab 1 should NOT have called detach
      expect((detachSpy as any)?.mock?.calls?.length || 0).toBe(0);
    });

    it('Both tabs should have separate channel instances', async () => {
      console.log('[PART 3] Testing: Separate channel instances\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      const tab1Channel = tab1.current.channel;
      const tab2Channel = tab2.current.channel;

      console.log('[TEST] Tab 1 channel instance ID:', (tab1Channel as any)?._instanceId);
      console.log('[TEST] Tab 2 channel instance ID:', (tab2Channel as any)?._instanceId);
      console.log('[TEST] Are they the same object?', tab1Channel === tab2Channel);

      // Channels should be different instances
      expect(tab1Channel).not.toBe(tab2Channel);
      expect((tab1Channel as any)?._instanceId).not.toBe((tab2Channel as any)?._instanceId);
    });
  });

  // ==========================================================================
  // PART 4: CLIENT ID VERIFICATION
  // ==========================================================================

  describe('Part 4: Client ID Matching', () => {
    it('localPlayerId should match presence clientId', async () => {
      console.log('[PART 4] Testing: localPlayerId matches presence\n');

      const { result } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await result.current.createRoom();
      });

      await waitFor(() => expect(result.current.isConnected).toBe(true));

      const localId = result.current.localPlayerId;
      const presenceMembers = roomPresenceMap.get(roomId) || [];
      const presenceClientId = presenceMembers[0]?.clientId;

      console.log('[TEST] localPlayerId:', localId);
      console.log('[TEST] presence clientId:', presenceClientId);

      expect(localId).toBe(presenceClientId);
    });

    it('Each tab should have unique client ID', async () => {
      console.log('[PART 4] Testing: Unique client IDs per tab\n');

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      const tab1Id = tab1.current.localPlayerId;
      const tab2Id = tab2.current.localPlayerId;

      console.log('[TEST] Tab 1 ID:', tab1Id);
      console.log('[TEST] Tab 2 ID:', tab2Id);
      console.log('[TEST] Are they different?', tab1Id !== tab2Id);

      expect(tab1Id).not.toBe(tab2Id);
    });
  });

  // ==========================================================================
  // PART 5: INTEGRATION TEST - FULL FLOW
  // ==========================================================================

  describe('Part 5: Full Two-Player Flow', () => {
    it('should allow two players to join and play', async () => {
      console.log('\n========== FULL FLOW TEST ==========');

      // STEP 1: Tab 1 creates room
      console.log('[STEP 1] Tab 1 creating room...');
      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      console.log('[STEP 1] Room created:', roomId);
      console.log('[STEP 1] Tab 1 localPlayerId:', tab1.current.localPlayerId);
      console.log('[STEP 1] Tab 1 playerRole:', tab1.current.playerRole);
      console.log('[STEP 1] Tab 1 roomState:', JSON.stringify(tab1.current.roomState, null, 2));

      expect(tab1.current.playerRole).toBe('X');
      expect(tab1.current.roomState.playerXId).toBe(tab1.current.localPlayerId);
      expect(tab1.current.roomState.playerOId).toBeNull();

      // STEP 2: Tab 2 joins room
      console.log('\n[STEP 2] Tab 2 joining room...');
      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      console.log('[STEP 2] Tab 2 localPlayerId:', tab2.current.localPlayerId);
      console.log('[STEP 2] Tab 2 playerRole:', tab2.current.playerRole);
      console.log('[STEP 2] Tab 2 roomState:', JSON.stringify(tab2.current.roomState, null, 2));

      // Wait for presence to sync
      await waitFor(() => {
        const members = roomPresenceMap.get(roomId) || [];
        return members.length === 2;
      }, { timeout: 2000 });

      // CRITICAL CHECKS
      console.log('\n[CRITICAL] Tab 1 after Tab 2 joins:');
      console.log('[CRITICAL] Tab 1 playerRole:', tab1.current.playerRole);
      console.log('[CRITICAL] Tab 1 channel state:', tab1.current.channel?.state);
      console.log('[CRITICAL] Tab 1 isConnected:', tab1.current.isConnected);
      console.log('[CRITICAL] Tab 1 roomState:', JSON.stringify(tab1.current.roomState, null, 2));

      // Tab 1 should STILL be Player X
      expect(tab1.current.playerRole).toBe('X');
      expect(tab1.current.channel?.state).toBe('attached');
      expect(tab1.current.isConnected).toBe(true);

      // Tab 2 should be Player O (NOT spectator)
      expect(tab2.current.playerRole).toBe('O');
      expect(tab2.current.playerRole).not.toBe('spectator');

      // Both should see 2 players
      await waitFor(() => {
        expect(tab1.current.roomState.playerXId).toBe(tab1.current.localPlayerId);
        expect(tab1.current.roomState.playerOId).toBe(tab2.current.localPlayerId);
      }, { timeout: 2000 });

      await waitFor(() => {
        expect(tab2.current.roomState.playerXId).toBe(tab1.current.localPlayerId);
        expect(tab2.current.roomState.playerOId).toBe(tab2.current.localPlayerId);
      }, { timeout: 2000 });

      console.log('\n[FINAL] Both players connected correctly');
      console.log('[FINAL] Player X:', tab1.current.roomState.playerXId);
      console.log('[FINAL] Player O:', tab1.current.roomState.playerOId);
      console.log('[FINAL] Spectators:', tab1.current.roomState.spectatorIds.length);

      expect(tab1.current.roomState.spectatorIds).toHaveLength(0);

      console.log('\n========== END FULL FLOW TEST ==========\n');
    });
  });

  // ==========================================================================
  // PART 6: ACTUAL CODE INSPECTION
  // ==========================================================================

  describe('Part 6: Actual Implementation Behavior', () => {
    it('should show how determineRole actually behaves', async () => {
      console.log('[PART 6] Testing: Actual determineRole behavior\n');

      // Scenario 1: First player joins empty room
      console.log('\n[SCENARIO 1] First player joins empty room:');
      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      const members1 = roomPresenceMap.get(roomId) || [];
      console.log('  Presence members:', members1.map(m => `${m.clientId}:${m.data.role}`));
      console.log('  Tab 1 determined role:', tab1.current.playerRole);
      console.log('  Expected: X');
      console.log('  Actual matches expected?', tab1.current.playerRole === 'X');

      // Scenario 2: Second player joins
      console.log('\n[SCENARIO 2] Second player joins (X exists):');
      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      const members2 = roomPresenceMap.get(roomId) || [];
      console.log('  Presence members:', members2.map(m => `${m.clientId}:${m.data.role}`));
      console.log('  Tab 2 determined role:', tab2.current.playerRole);
      console.log('  Expected: O');
      console.log('  Actual matches expected?', tab2.current.playerRole === 'O');

      // Scenario 3: Third player joins
      console.log('\n[SCENARIO 3] Third player joins (X and O exist):');
      const { result: tab3 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab3.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab3.current.isConnected).toBe(true));

      const members3 = roomPresenceMap.get(roomId) || [];
      console.log('  Presence members:', members3.map(m => `${m.clientId}:${m.data.role}`));
      console.log('  Tab 3 determined role:', tab3.current.playerRole);
      console.log('  Expected: spectator');
      console.log('  Actual matches expected?', tab3.current.playerRole === 'spectator');

      // Expected behavior
      expect(tab1.current.playerRole).toBe('X');
      expect(tab2.current.playerRole).toBe('O');
      expect(tab3.current.playerRole).toBe('spectator');
    });

    it('should show presence callbacks firing correctly', async () => {
      console.log('[PART 6] Testing: Presence callback behavior\n');

      const tab1CallbackCount = 0;
      const tab2CallbackCount = 0;

      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      // Monitor callbacks
      const roomCallbacks = presenceCallbacksMap.get(roomId);
      console.log('[TEST] Presence callbacks registered for room:', roomCallbacks?.size || 0);

      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      console.log('[TEST] Presence callbacks after Tab 2 joins:', roomCallbacks?.size || 0);
      console.log('[TEST] Both tabs should have registered callbacks');

      // Both tabs should have presence callbacks
      expect(roomCallbacks?.size).toBeGreaterThan(0);
    });

    it('should show the exact bug manifestation', async () => {
      console.log('[PART 6] BUG MANIFESTATION TEST\n');
      console.log('This test documents the EXACT bug we are seeing:\n');

      // Tab 1 creates room
      const { result: tab1 } = renderHook(() => useRoom(null));

      let roomId: string = '';
      await act(async () => {
        roomId = await tab1.current.createRoom();
      });

      await waitFor(() => expect(tab1.current.isConnected).toBe(true));

      console.log('[BUG STEP 1] Tab 1 creates room');
      console.log('  Tab 1 role:', tab1.current.playerRole, '(expected: X)');
      console.log('  Tab 1 connected:', tab1.current.isConnected, '(expected: true)');
      console.log('  playerXId:', tab1.current.roomState.playerXId);
      console.log('  playerOId:', tab1.current.roomState.playerOId, '(expected: null)');

      const beforeState = {
        role: tab1.current.playerRole,
        connected: tab1.current.isConnected,
        channelExists: !!tab1.current.channel,
      };

      // Tab 2 joins
      console.log('\n[BUG STEP 2] Tab 2 joins room');
      const { result: tab2 } = renderHook(() => useRoom(null));

      await act(async () => {
        await tab2.current.joinRoom(roomId);
      });

      await waitFor(() => expect(tab2.current.isConnected).toBe(true));

      // Give time for bug to manifest
      await new Promise(resolve => setTimeout(resolve, 200));

      console.log('\n[BUG STEP 3] After Tab 2 joins - checking Tab 1 state');
      console.log('  Tab 1 role:', tab1.current.playerRole, '(should still be X)');
      console.log('  Tab 1 connected:', tab1.current.isConnected, '(should still be true)');
      console.log('  Tab 1 channel exists:', !!tab1.current.channel, '(should still be true)');

      console.log('\n[BUG STEP 4] Checking Tab 2 state');
      console.log('  Tab 2 role:', tab2.current.playerRole, '(should be O, NOT spectator)');
      console.log('  Tab 2 connected:', tab2.current.isConnected, '(expected: true)');

      console.log('\n[BUG ANALYSIS]');
      console.log('  Tab 1 disconnected?', beforeState.connected && !tab1.current.isConnected);
      console.log('  Tab 1 lost channel?', beforeState.channelExists && !tab1.current.channel);
      console.log('  Tab 1 lost role?', beforeState.role === 'X' && tab1.current.playerRole !== 'X');
      console.log('  Tab 2 is spectator?', tab2.current.playerRole === 'spectator');

      const members = roomPresenceMap.get(roomId) || [];
      console.log('\n[BUG EVIDENCE] Presence state:');
      members.forEach((m, i) => {
        console.log(`  Member ${i + 1}: ${m.clientId} - ${m.data.role}`);
      });

      // The assertions that will fail if bug exists
      try {
        expect(tab1.current.playerRole).toBe('X');
        expect(tab1.current.isConnected).toBe(true);
        expect(tab1.current.channel).toBeTruthy();
        expect(tab2.current.playerRole).toBe('O');
        expect(tab2.current.playerRole).not.toBe('spectator');

        console.log('\n✓ NO BUG DETECTED (all assertions passed)');
      } catch (error) {
        console.log('\n✗ BUG CONFIRMED:', (error as Error).message);
        throw error;
      }
    });
  });
});
